<?php

namespace ContainerWataF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C6FFJJEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C6FFJJE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C6FFJJE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'author' => ['privates', '.errored..service_locator.C6FFJJE.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.C6FFJJE": it references class "App\\Entity\\Author" but no such service exists.'],
            'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
        ], [
            'author' => 'App\\Entity\\Author',
            'authorRepository' => 'App\\Repository\\AuthorRepository',
        ]);
    }
}
