<?php

namespace ContainerWataF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FMCqXQ_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FMCqXQ.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FMCqXQ.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookCategory' => ['privates', '.errored..service_locator.FMCqXQ..App\\Entity\\BookCategory', NULL, 'Cannot autowire service ".service_locator.FMCqXQ.": it references class "App\\Entity\\BookCategory" but no such service exists.'],
            'bookCategoryRepository' => ['privates', 'App\\Repository\\BookCategoryRepository', 'getBookCategoryRepositoryService', true],
        ], [
            'bookCategory' => 'App\\Entity\\BookCategory',
            'bookCategoryRepository' => 'App\\Repository\\BookCategoryRepository',
        ]);
    }
}
