<?php

namespace ContainerWataF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KN2qd6PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KN2qd6P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KN2qd6P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookPage' => ['privates', '.errored..service_locator.KN2qd6P.App\\Entity\\BookPage', NULL, 'Cannot autowire service ".service_locator.KN2qd6P": it references class "App\\Entity\\BookPage" but no such service exists.'],
            'bookPageRepository' => ['privates', 'App\\Repository\\BookPageRepository', 'getBookPageRepositoryService', true],
        ], [
            'bookPage' => 'App\\Entity\\BookPage',
            'bookPageRepository' => 'App\\Repository\\BookPageRepository',
        ]);
    }
}
