<?php

namespace ContainerWataF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookPageTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BookPageType' shared autowired service.
     *
     * @return \App\Form\BookPageType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/BookPageType.php';

        return $container->privates['App\\Form\\BookPageType'] = new \App\Form\BookPageType();
    }
}
