<?php

namespace ContainerWataF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookPageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KN2qd6P.App\Entity\BookPage' shared service.
     *
     * @return \App\Entity\BookPage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KN2qd6P": it references class "App\\Entity\\BookPage" but no such service exists.');
    }
}
