<?php

namespace ContainerWataF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CarouselType' shared autowired service.
     *
     * @return \App\Form\CarouselType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CarouselType.php';

        return $container->privates['App\\Form\\CarouselType'] = new \App\Form\CarouselType();
    }
}
