<?php

namespace ContainerWataF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ELLkueh.App\Entity\Home' shared service.
     *
     * @return \App\Entity\Home
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ELLkueh": it references class "App\\Entity\\Home" but no such service exists.');
    }
}
