<?php

namespace ContainerW25aViW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PN7RnQuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pN7RnQu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pN7RnQu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookPage' => ['privates', '.errored..service_locator.pN7RnQu.App\\Entity\\BookPage', NULL, 'Cannot autowire service ".service_locator.pN7RnQu": it references class "App\\Entity\\BookPage" but no such service exists.'],
        ], [
            'bookPage' => 'App\\Entity\\BookPage',
        ]);
    }
}
