<?php

namespace ContainerW25aViW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6ugKy2b.App\Entity\BookCategory' shared service.
     *
     * @return \App\Entity\BookCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6ugKy2b": it references class "App\\Entity\\BookCategory" but no such service exists.');
    }
}
