<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWataF3N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWataF3N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWataF3N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWataF3N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWataF3N\App_KernelDevDebugContainer([
    'container.build_hash' => 'WataF3N',
    'container.build_id' => '190321c9',
    'container.build_time' => 1666441147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWataF3N');
